import Navigation from "@/components/Drawer/Navigation"

type Props = {
  children: React.ReactNode
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
